CREATE TABLE IF NOT EXISTS listing_images (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    listing_id INTEGER NOT NULL,
    listing_image TEXT NOT NULL,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (listing_id) REFERENCES listing(id)
)