CREATE TABLE IF NOT EXISTS listing(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price double NOT NULL,
    description VARCHAR(255) NOT NULL
    is_deleted BOOLEAN DEFAULT false
    is_traded BOOLEAN DEFAULT false
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
)